controller_manager: # Controller Manager bir ROS node ve ayarlar node adÄ±na gÃ¶re yazÄ±lÄ±r
  ros_parameters:
  update_rates: 100
  use_sim_time: true

  joint_state_broadcaster:
    type: joint_state_broadcaster/ JointStateBroadcaster 

    #Bu ne yapar? Tekerlerin: pozisyonunu, hÄ±zÄ±nÄ± topic olarak yayÄ±nlar

  simple_velocity_controller:
    type: velocity_controller/ JointGroupVelocityController

  
  simple_velocity_controller:  # Bu controller hangi jointâ€™leri sÃ¼recek?
    ros_parameters:
      joints:
        - left_wheel_joint
        - right_wheel_joint


        # ğŸ“Œ MantÄ±k:
        # Gazebo â†’ ROS2 Control â†’ Controller Manager
        # â€œBu YAMLâ€™Ä± kullanâ€